import { useState } from "react";
import { Copy, FileText, Download, Check, ExternalLink } from "lucide-react";
import { motion } from "framer-motion";

interface SummaryDisplayProps {
    title: string;
    url?: string;
    summary: string;
    wordCount?: number;
    onDownloadPDF: () => void;
    onDownloadDOCX: () => void;
}

export function SummaryDisplay({ title, url, summary, wordCount, onDownloadPDF, onDownloadDOCX }: SummaryDisplayProps) {
    const [isCopied, setIsCopied] = useState(false);

    const handleCopy = () => {
        const text = `${title}\n\n${summary}`;
        navigator.clipboard.writeText(text);
        setIsCopied(true);
        setTimeout(() => setIsCopied(false), 2000);
    };

    const displayUrl = url ? new URL(url).hostname + new URL(url).pathname : "";

    return (
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }} className="card overflow-hidden">
            {/* Card Header */}
            <div className="px-6 md:px-8 pt-6 md:pt-8 pb-4 border-b border-dashed border-border flex flex-col sm:flex-row justify-between items-start gap-4">
                <div className="min-w-0 flex-1">
                    <h3 className="text-xl md:text-2xl font-bold text-foreground mb-1 line-clamp-2">{title}</h3>
                    {url && (
                        <a href={url} target="_blank" rel="noopener noreferrer" className="text-sm text-[#13a4ec] hover:underline flex items-center gap-1">
                            {displayUrl}
                            <ExternalLink size={14} />
                        </a>
                    )}
                </div>
                <div className="badge-success shrink-0">Summary Ready</div>
            </div>

            {/* Main Content Body */}
            <div className="px-6 md:px-8 py-6 text-foreground/80 text-base md:text-md leading-relaxed">
                {summary ? <p className="whitespace-pre-wrap">{summary}</p> : <p className="text-muted-foreground italic">No summary generated yet.</p>}
            </div>

            {/* Bottom Toolbar */}
            <div className="bg-muted/50 px-4 md:px-6 py-4 flex flex-col sm:flex-row items-center justify-between border-t border-border gap-4">
                {/* Meta info */}
                <div className="text-xs text-muted-foreground font-medium">{wordCount ? `~ ${wordCount} words` : "Generated by AI"}</div>

                {/* Actions */}
                <div className="flex items-center gap-1">
                    <button onClick={handleCopy} className="action-btn" title="Copy to clipboard">
                        {isCopied ? <Check size={18} className="text-green-500" /> : <Copy size={18} />}
                        <span className="hidden sm:inline">Copy</span>
                    </button>
                    <div className="h-4 w-px bg-border mx-1" />
                    <button onClick={onDownloadPDF} className="action-btn" title="Download PDF">
                        <Download size={18} />
                        <span className="hidden sm:inline">PDF</span>
                    </button>
                    <button onClick={onDownloadDOCX} className="action-btn" title="Download DOCX">
                        <FileText size={18} />
                        <span className="hidden sm:inline">DOC</span>
                    </button>
                </div>
            </div>
        </motion.div>
    );
}
